### ISSUE TITLE
[Fix] Fix Terms Modal

### ISSUE THREAD

**Issue by da-in** [develo-pool/app_pool_frontend#157]
### Problems
Terms Modal (약관 모달) IOS에서 작동하지 않음

### Todo
~Modal IOS 동작~
- [x] Link Terms
- [x] ~Modal Close Button Area 수정 + Safe Area View~

### Etc
- [x] Auth Button Padding 제거 및 Align 변경
- [x] 이용약관 내용중 "전화번호, " 삭제 요청 반영
